from typing import List

COMPANY_NAMES: List[str] = [
    "Acme Corporation",
    "TechVision Inc",
    "Global Solutions Ltd",
    "Innovate Systems",
    "DataFlow Technologies",
    "CloudScale Enterprises",
    "NextGen Analytics",
    "Quantum Software",
    "Apex Consulting Group",
    "Velocity Partners",
    "Summit Ventures",
    "Catalyst Industries",
    "Zenith Corporation",
    "Horizon Technologies",
    "Pulse Digital",
    "Nexus Solutions",
    "Vortex Systems",
    "Prism Analytics",
    "Atlas Enterprises",
    "Titan Group",
    "Phoenix Solutions",
    "Echo Technologies",
    "Nova Systems",
    "Vertex Corporation",
    "Sigma Consulting",
    "Delta Partners",
    "Omega Industries",
    "Prime Solutions",
    "Core Technologies",
    "Edge Systems",
    "Fusion Analytics",
    "Orbit Corporation",
    "Stellar Group",
    "Unity Solutions",
    "Visionary Technologies",
    "Bright Future Inc",
    "Dynamic Systems",
    "Synergy Partners",
    "Momentum Corporation",
    "Pinnacle Solutions",
    "Endeavor Technologies",
    "Keystone Industries",
    "Meridian Group",
    "Navigator Solutions",
    "Paradigm Systems",
    "Quantum Leap Inc",
    "Resilient Technologies",
    "Spectrum Corporation",
    "Trailblazer Group",
    "Uplift Solutions",
]

INDUSTRIES: List[str] = [
    "Technology",
    "Healthcare",
    "Finance",
    "Manufacturing",
    "Retail",
    "Education",
    "Real Estate",
    "Telecommunications",
    "Energy",
    "Transportation",
    "Media",
    "Hospitality",
    "Construction",
    "Agriculture",
    "Automotive",
    "Pharmaceuticals",
    "Insurance",
    "Consulting",
    "Legal Services",
    "Entertainment",
]

FIRST_NAMES: List[str] = [
    "Stephanie",
    "Aman",
    "Gabriela",
    "Michael",
    "Sarah",
    "David",
    "Jennifer",
    "Robert",
    "Emily",
    "James",
    "Jessica",
    "William",
    "Amanda",
    "Christopher",
    "Lisa",
    "Daniel",
    "Michelle",
    "Matthew",
    "Ashley",
    "Andrew",
    "Rachel",
    "Joshua",
    "Lauren",
    "Kevin",
    "Nicole",
    "Brian",
    "Elizabeth",
    "Ryan",
    "Samantha",
    "Jason",
    "Megan",
    "Brandon",
    "Hannah",
    "Tyler",
    "Alexis",
    "Eric",
    "Rebecca",
    "Jacob",
    "Taylor",
    "Nicholas",
]

LAST_NAMES: List[str] = [
    "Wong",
    "Sharma",
    "Chan",
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Thompson",
    "White",
    "Harris",
    "Clark",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
]

OWNERS: List[str] = [
    "stephanie.wong",
    "aman.sharma",
    "gabriela.chan",
    "michael.smith",
    "sarah.johnson",
    "david.williams",
    "jennifer.brown",
    "robert.jones",
    "emily.garcia",
    "james.miller",
]

JOB_TITLES: List[str] = [
    "CEO",
    "CTO",
    "CFO",
    "VP of Sales",
    "VP of Engineering",
    "VP of Operations",
    "Director of Marketing",
    "Director of Product",
    "Head of Business Development",
    "Senior Account Executive",
    "Account Manager",
    "Sales Manager",
    "Product Manager",
    "Engineering Manager",
    "Project Manager",
    "Business Analyst",
    "Solutions Architect",
    "Technical Lead",
    "Operations Manager",
    "Customer Success Manager",
]

OPPORTUNITY_NAME_TEMPLATES: List[str] = [
    "{company} - FY{year} Renewal",
    "{company} - Enterprise License",
    "{company} - Platform Migration",
    "{company} - Cloud Infrastructure",
    "{company} - Digital Transformation",
    "{company} - Analytics Suite",
    "{company} - Security Upgrade",
    "{company} - Integration Services",
    "{company} - Consulting Engagement",
    "{company} - Training Program",
    "{company} - Support Contract",
    "{company} - Custom Development",
    "{company} - API Access",
    "{company} - Premium Features",
    "{company} - Expansion Deal",
]

QUOTE_VERSION_PREFIXES: List[str] = [
    "Q",
    "QT",
    "QUOTE",
    "EST",
    "PROPOSAL",
]

DOCUMENT_TYPES: List[str] = [
    "contract",
    "proposal",
    "invoice",
    "sow",
    "msa",
    "nda",
    "amendment",
    "exhibit",
    "terms",
    "pricing",
]

FILE_EXTENSIONS: List[str] = [
    "pdf",
    "docx",
    "xlsx",
    "pptx",
    "csv",
    "txt",
]

NOTE_TEMPLATES: List[str] = [
    "Follow-up scheduled for next week",
    "Client requested additional information on pricing",
    "Technical requirements discussed in detail",
    "Stakeholder meeting went well, moving to next stage",
    "Concerns raised about timeline, need to address",
    "Budget approved, awaiting final sign-off",
    "Competitor mentioned during call",
    "Decision maker on vacation, resuming next month",
    "Positive feedback on demo",
    "Legal review in progress",
]

STREET_NAMES: List[str] = [
    "Main Street",
    "Market Street",
    "Oak Avenue",
    "Park Avenue",
    "Broadway",
    "Washington Street",
    "Maple Drive",
    "Cedar Lane",
    "Pine Street",
    "Elm Avenue",
]

CITIES: List[str] = [
    "San Francisco",
    "New York",
    "Austin",
    "Seattle",
    "Boston",
    "Chicago",
    "Los Angeles",
    "Denver",
    "Atlanta",
    "Portland",
    "Miami",
    "Dallas",
    "Phoenix",
    "San Diego",
    "Philadelphia",
]

STATES: List[str] = [
    "CA",
    "NY",
    "TX",
    "WA",
    "MA",
    "IL",
    "CO",
    "GA",
    "OR",
    "FL",
    "AZ",
    "PA",
]
